# stations.py
stations = {
    "VTV1 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv1-hd.epi",
    "VTV2 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv2-hd.epi",
    "VTV3 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv3-hd.epi",
    "VTV4 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv4-hd.epi",
    "VTV5 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv5-hd.epi",
    "VTV6 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv6-hd.epi",
    "VTV8 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv8-hd.epi",
    "VTV9": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv9.epi",
    "HTV7 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv7-hd.epi",
    "HTV9 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv9-hd.epi",
    "HTV1": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv1.epi",
    "HTV2": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv2.epi",
    "HTV3": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv3.epi",
    "HTV4": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv4.epi",
    "HTV Thể Thao": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv-the-thao.epi",
    "HTV Co.op": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv-coop.epi",
    "THVL1": "https://baomoi.com/tien-ich-lich-truyen-hinh-thvl1.epi",
    "THVL2": "https://baomoi.com/tien-ich-lich-truyen-hinh-thvl2.epi",
    "THVL3": "https://baomoi.com/tien-ich-lich-truyen-hinh-thvl3.epi",
    "THVL4": "https://baomoi.com/tien-ich-lich-truyen-hinh-thvl4.epi",
    "VTC1": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc1.epi",
    "VTC2": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc2.epi",
    "VTC3": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc3.epi",
    "VTC4": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc4.epi",
    "VTC5": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc5.epi",
    "VTC6": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc6.epi",
    "VTC7": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc7.epi",
    "VTC8": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc8.epi",
    "VTC9": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc9.epi",
    "VTC10": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc10.epi",
    "VTC11": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc11.epi",
    "VTC12": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc12.epi",
    "VTC13": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc13.epi",
    "VTC14": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc14.epi",
    "VTC16": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtc16.epi",
    "HanoiTV1": "https://baomoi.com/tien-ich-lich-truyen-hinh-hanoitv1.epi",
    "HanoiTV2": "https://baomoi.com/tien-ich-lich-truyen-hinh-hanoitv2.epi",
    "Hải Phòng": "https://baomoi.com/tien-ich-lich-truyen-hinh-haiphong.epi",
    "Nam Định": "https://baomoi.com/tien-ich-lich-truyen-hinh-namdinh.epi",
    "Ninh Bình": "https://baomoi.com/tien-ich-lich-truyen-hinh-ninhbinh.epi",
    "Thanh Hóa": "https://baomoi.com/tien-ich-lich-truyen-hinh-thanhhoa.epi",
    "Nghệ An": "https://baomoi.com/tien-ich-lich-truyen-hinh-nghean.epi",
    "Hà Tĩnh": "https://baomoi.com/tien-ich-lich-truyen-hinh-hatinh.epi",
    "Quảng Bình": "https://baomoi.com/tien-ich-lich-truyen-hinh-quangbinh.epi",
    "Quảng Trị": "https://baomoi.com/tien-ich-lich-truyen-hinh-quangtri.epi",
    "Thừa Thiên Huế": "https://baomoi.com/tien-ich-lich-truyen-hinh-thuathienhue.epi",
    "Đà Nẵng": "https://baomoi.com/tien-ich-lich-truyen-hinh-danang.epi",
    "Quảng Nam": "https://baomoi.com/tien-ich-lich-truyen-hinh-quangnam.epi",
    "Quảng Ngãi": "https://baomoi.com/tien-ich-lich-truyen-hinh-quangngai.epi",
    "Bình Định": "https://baomoi.com/tien-ich-lich-truyen-hinh-binhdinh.epi",
    "Khánh Hòa": "https://baomoi.com/tien-ich-lich-truyen-hinh-khanhhoa.epi",
    "Bình Thuận": "https://baomoi.com/tien-ich-lich-truyen-hinh-binhthuan.epi",
    "Đắk Lắk": "https://baomoi.com/tien-ich-lich-truyen-hinh-daklak.epi",
    "Đắk Nông": "https://baomoi.com/tien-ich-lich-truyen-hinh-daknong.epi",
    "Gia Lai": "https://baomoi.com/tien-ich-lich-truyen-hinh-gialai.epi",
    "Kon Tum": "https://baomoi.com/tien-ich-lich-truyen-hinh-kontum.epi",
    "Bình Dương": "https://baomoi.com/tien-ich-lich-truyen-hinh-binhduong.epi",
    "Đồng Nai": "https://baomoi.com/tien-ich-lich-truyen-hinh-dongnai.epi",
    "Cần Thơ": "https://baomoi.com/tien-ich-lich-truyen-hinh-cantho.epi",
    "Sóc Trăng": "https://baomoi.com/tien-ich-lich-truyen-hinh-soctrang.epi",
    "Bạc Liêu": "https://baomoi.com/tien-ich-lich-truyen-hinh-baclieu.epi",
    "Cà Mau": "https://baomoi.com/tien-ich-lich-truyen-hinh-camau.epi",
    "Vĩnh Phúc": "https://baomoi.com/tien-ich-lich-truyen-hinh-vinhphuc.epi",
}
