# stations.py
# === Stations đầy đủ ===
stations = {
    "VTV1 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv1-hd.epi",
    "VTV3 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv3-hd.epi",
    "VTV6 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv6-hd.epi",
    "VTV2 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv2-hd.epi",
    "VTV4 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv4-hd.epi",
    "VTV5 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv5-hd.epi",
    "VTV8 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv8-hd.epi",
    "VTV9": "https://baomoi.com/tien-ich-lich-truyen-hinh-vtv9.epi",
    "An Giang ATV": "https://baomoi.com/tien-ich-lich-truyen-hinh-angiangtv-atv.epi",
    "ANTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-antv.epi",
    "Bắc Giang BGTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-bacgiangtv-bgtv.epi",
    "Bắc Kạn TBK": "https://baomoi.com/tien-ich-lich-truyen-hinh-backantv-tbk.epi",
    "Bạc Liêu BTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-baclieutv-btv.epi",
    "Bắc Ninh BTV HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-bacninhtv-btv-hd.epi",
    "Bến Tre THBT": "https://baomoi.com/tien-ich-lich-truyen-hinh-bentretv-thbt.epi",
    "Bình Dương 1": "https://baomoi.com/tien-ich-lich-truyen-hinh-binhduongtv1-btv1-hd.epi",
    "Bình Dương 2": "https://baomoi.com/tien-ich-lich-truyen-hinh-binhduongtv2-btv2.epi",
    "Bình Phước BPTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-binhphuoctv-bptv.epi",
    "Bình Thuận BTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-binhthuantv-btv.epi",
    "Cà Mau CTV1": "https://baomoi.com/tien-ich-lich-truyen-hinh-camautv-ctv1.epi",
    "Cần Thơ THTPCT": "https://baomoi.com/tien-ich-lich-truyen-hinh-canthotv-thtpct.epi",
    "Cao Bằng CRTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-caobangtv-crtv.epi",
    "Đắk Lắk DRT": "https://baomoi.com/tien-ich-lich-truyen-hinh-daklaktv-drt.epi",
    "Đắk Nông PTD": "https://baomoi.com/tien-ich-lich-truyen-hinh-daknongtv-ptd.epi",
    "Đà Nẵng DRT1": "https://baomoi.com/tien-ich-lich-truyen-hinh-danangtv1-drt1.epi",
    "Đà Nẵng DRT2": "https://baomoi.com/tien-ich-lich-truyen-hinh-danangtv2-drt2.epi",
    "Đồng Nai 1": "https://baomoi.com/tien-ich-lich-truyen-hinh-dongnaitv1-dn1-hd.epi",
    "Đồng Nai 2": "https://baomoi.com/tien-ich-lich-truyen-hinh-dongnaitv2-dn2.epi",
    "Đồng Tháp THĐL": "https://baomoi.com/tien-ich-lich-truyen-hinh-dongthaptv-thdl.epi",
    "Gia Lai THGL": "https://baomoi.com/tien-ich-lich-truyen-hinh-gialaitv-thgl.epi",
    "Hà Giang HGTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-hagiangtv-hgtv.epi",
    "Hải Phòng THP HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-haiphongtv-thp-hd.epi",
    "Hà Nội 1": "https://baomoi.com/tien-ich-lich-truyen-hinh-hanoitv1-hd.epi",
    "Hà Nội 2": "https://baomoi.com/tien-ich-lich-truyen-hinh-hanoitv2-hd.epi",
    "Hà Tĩnh HTTV HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-hatinhtv-httv-hd.epi",
    "Hậu Giang HGV": "https://baomoi.com/tien-ich-lich-truyen-hinh-haugiangtv-hgv.epi",
    "Hòa Bình HBTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-hoabinhtv-hbtv.epi",
    "HTV1": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv1.epi",
    "HTV2 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv2-hd.epi",
    "HTV4": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv4.epi",
    "HTV7 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv7-hd.epi",
    "HTV9 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-htv9-hd.epi",
    "Huế TRT1": "https://baomoi.com/tien-ich-lich-truyen-hinh-huetv1-trt1.epi",
    "Hưng Yên HY HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-hungyentv-hy-hd.epi",
    "Khánh Hòa KTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-khanhhoatv-ktv.epi",
    "Kon Tum KRT": "https://baomoi.com/tien-ich-lich-truyen-hinh-kontumtv-krt.epi",
    "Lâm Đồng LDTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-lamdongtv-ldtv.epi",
    "Lạng Sơn LSTV1": "https://baomoi.com/tien-ich-lich-truyen-hinh-langsontv1-lstv1.epi",
    "Long An LA34": "https://baomoi.com/tien-ich-lich-truyen-hinh-longantv-la34.epi",
    "Nam Định NTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-namdinhtv-ntv.epi",
    "Phú Yên PTP": "https://baomoi.com/tien-ich-lich-truyen-hinh-phuyentv-ptp.epi",
    "QPVN HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-qpvn-hd.epi",
    "Quảng Bình QBTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-quangbinhtv-qbtv.epi",
    "Quảng Nam QRT": "https://baomoi.com/tien-ich-lich-truyen-hinh-quangnamtv-qrt.epi",
    "Quảng Ngãi PTQ1 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-quangngaitv-ptq1-hd.epi",
    "Quảng Ninh QTV1 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-quangninhtv1-qtv1-hd.epi",
    "Sơn La STV": "https://baomoi.com/tien-ich-lich-truyen-hinh-sonlatv-stv.epi",
    "Tây Ninh TTV11": "https://baomoi.com/tien-ich-lich-truyen-hinh-tayninhtv-ttv11.epi",
    "Thái Nguyên TV1 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-thainguyentv1-tv1-hd.epi",
    "Tiền Giang THTG": "https://baomoi.com/tien-ich-lich-truyen-hinh-tiengiangtv-thtg.epi",
    "Trà Vinh THTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-travinhtv-thtv.epi",
    "Tuyên Quang TTV": "https://baomoi.com/tien-ich-lich-truyen-hinh-tuyenquangtv-ttv.epi",
    "Vĩnh Long THVL1 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vinhlongtv1-thvl1-hd.epi",
    "Vĩnh Long THVL3 HD": "https://baomoi.com/tien-ich-lich-truyen-hinh-vinhlongtv3-thvl3-hd.epi",
    "Vĩnh Phúc VP": "https://baomoi.com/tien-ich-lich-truyen-hinh-vinhphuctv-vp.epi",
}
